application: secret-bay-570
version: 0-2
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest

handlers:
- url: /_ah/mail/.+
  script: emailhandler.application
  login: admin
- url: /.*
  script: landingpage.application


inbound_services:
- mail