application: secret-bay-570
version: 0-2
runtime: python27
api_version: 1
threadsafe: true

libraries:

- name: webapp2
  version: latest
  
- name: jinja2
  version: latest

handlers:

- url: /stylesheets
  static_dir: stylesheets
- url: /image
  static_dir: image
  
- url: /_ah/mail/.+
  script: emailhandler.application
  login: admin

- url: /posreport/.*
  script: webpositionreport.application
  login: required
  

- url: /newvessel
  script: pagehandler.application
  login: required
  
- url: /myvessel
  script: pagehandler.application
  login: required
  
- url: /.*
  script: pagehandler.application
  
inbound_services:

- mail