application: secret-bay-570
version: 0-3
runtime: python27
api_version: 1
threadsafe: true

libraries:

- name: webapp2
  version: latest
  
- name: jinja2
  version: latest

handlers:

- url: /stylesheets
  static_dir: stylesheets

- url: /image
  static_dir: image
  
- url: /_ah/mail/.+
  script: emailhandler.application
  login: admin

- url: /posreport/.*
  script: webpositionreport.application
  login: required
  

- url: /newvessel
  script: newvessel.application
  login: required
  
- url: /myvessel
  script: vessel.application
  login: required

- url: /vessellist
  script: vessellist.application

- url: /vessel/key/.+
  script: vessel.application

- url: /weather/waypoint/.+
  script: weather.application

- url: /.*
  script: pagehandler.application
  
inbound_services:

- mail
